export const IMMIGRANT_LIST_REQUEST = 'IMMIGRANT_LIST_REQUEST',
  IMMIGRANT_LIST_SUCCESS = 'IMMIGRANT_LIST_SUCCESS',
  IMMIGRANT_LIST_FAILED = 'IMMIGRANT_LIST_FAILED'

export const IMMIGRANT_DELETE_REQUEST = 'IMMIGRANT_DELETE_REQUEST',
  IMMIGRANT_DELETE_SUCCESS = 'IMMIGRANT_DELETE_SUCCESS',
  IMMIGRANT_DELETE_FAILED = 'IMMIGRANT_DELETE_FAILED'

export const SEARCH_IMMIGRANT_REQUEST = 'SEARCH_IMMIGRANT_REQUEST',
  SEARCH_IMMIGRANT_FAILED = 'SEARCH_IMMIGRANT_FAILED'
