export const IMMIGRANT_LIST_REQUEST = 'IMMIGRANT_LIST_REQUEST',
  IMMIGRANT_LIST_SUCCESS = 'IMMIGRANT_LIST_SUCCESS',
  IMMIGRANT_LIST_FAILED = 'IMMIGRANT_LIST_FAILED'

export const IMMIGRANT_DELETE_REQUEST = 'IMMIGRANT_DELETE_REQUEST',
  IMMIGRANT_DELETE_SUCCESS = 'IMMIGRANT_DELETE_SUCCESS',
  IMMIGRANT_DELETE_FAILED = 'IMMIGRANT_DELETE_FAILED',
  IMMIGRANT_LIST_RESET = 'IMMIGRANT_LIST_RESET'

export const BUSINESS_LIST_REQUEST = 'BUSINESS_LIST_REQUEST',
  BUSINESS_LIST_SUCCESS = 'BUSINESS_LIST_SUCCESS',
  BUSINESS_LIST_FAILED = 'BUSINESS_LIST_FAILED'

export const GENERAL_LIST_REQUEST = 'GENERAL_LIST_REQUEST',
  GENERAL_LIST_SUCCESS = 'GENERAL_LIST_SUCCESS',
  GENERAL_LIST_FAILED = 'GENERAL_LIST_FAILED'

export const UPDATE_IMMIGRANT_REQUEST = 'UPDATE_IMMIGRANT_REQUEST',
  UPDATE_GENERAL_SUCCESS = 'UPDATE_GENERAL_SUCCESS',
  UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS',
  UPDATE_IMMIGRANT_FAILED = 'UPDATE_IMMIGRANT_FAILED'

export const SEARCH_IMMIGRANT_REQUEST = 'SEARCH_IMMIGRANT_REQUEST',
  SEARCH_IMMIGRANT_FAILED = 'SEARCH_IMMIGRANT_FAILED'
